"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ArrowUpRight, ArrowRight, Globe2, Code2, Layers3, Smartphone, Check, Menu, X, Compass, LoaderCircle } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";

import { DustSurface } from "@/components/dust-surface";
import { CapabilityShowcase } from "@/components/capability-showcase";

type Language = "en" | "es";
const copy = {
 en: {
  nav: ["Services", "The approach", "Let's talk"], studio: "WEB DESIGN & DEVELOPMENT · SOUTHERN CALIFORNIA", title: ["Local roots.", "Digital", "possibilities."], intro: "Your business has something special. Let's build a website that shows it — and makes it easier for the right people to find you.", cta: "Let's build something", explore: "Explore the services", note: "Your vision. Thoughtful design. Real code.", photo: "THE GOLDEN STATE. A FRESH PERSPECTIVE.", badge: ["Good ideas speak", "both languages."], band: "Built for the businesses that make SoCal, SoCal.", regions: "Orange County · Los Angeles · San Diego · Inland Empire",
  eyebrow: "01 / WHAT WE DO", heading: "A better home\nfor your business online.", serviceIntro: "Starting from scratch or ready for your next chapter? Build only what your business needs, with room to grow.", services: [
   {title:"Websites with purpose.", desc:"A distinct, thoughtfully built website that tells your story and turns interest into a conversation.", tags:["Business websites","Landing pages","Mobile-first design"]},
   {title:"A fresh start online.", desc:"An outdated website shouldn't hold you back. Give your business a clearer message and a better experience.", tags:["Website redesigns","Speed & usability","Content structure"]},
   {title:"Beyond the brochure.", desc:"When your business needs more, connect the tools and workflows that keep your day moving.", tags:["Custom web apps","Business integrations","Workflow tools"]}
  ], serviceCta: "Tell us what you need", whyEyebrow: "02 / BUILT AROUND YOU", whyTitle: "A little taste of\nwhat’s possible.", whyText: "Explore working examples of the pages and tools we can build around your business. Try the controls, find what fits, and tell us your idea—in English or Spanish.", whyItems: ["Direct communication with your developer","A clear scope before development begins","Designed for your customers, on every screen"], languageSmall: "FROM THE FIRST HOLA TO LAUNCH DAY.", processEyebrow: "03 / HOW IT COMES TOGETHER", processTitle: "Big ideas. Clear next steps.", steps: [
   {title:"Let's talk.",text:"Tell us about your business, your customers, and what you want your website to do."},
   {title:"Make it yours.",text:"Agree on the scope, explore the design, and watch your website come together with room for your feedback."},
   {title:"Go live.",text:"Review the details, connect your domain, and launch with a walkthrough of your new website."}
  ], contactEyebrow:"04 / YOUR NEXT CHAPTER", contactTitle:"Something great\nstarts with hello.", contactText:"A new business. A long-overdue refresh. An idea on a napkin. Tell us what you have in mind.", contactNote:"English or español. Whatever feels like you.", name:"Your name", email:"Email address", business:"Business name (optional)", need:"What can we help with?", choose:"Choose a service", options:["A new website","A website redesign","A web app or integration","Let's figure it out together"], project:"Tell us a little about your project", placeholder:"What do you do, and what would you like to build?", submit:"Send project inquiry", sending:"Sending your inquiry…", privacy:"By sending, you agree to be contacted about your project. Your details will be stored to manage this inquiry.", success:"Your next chapter is in motion.", successText:"Your inquiry has been saved. We'll use the email you provided to discuss your project.", again:"Send another inquiry", error:"Your inquiry couldn't be saved. Please try again — your details are still here.", rate:"You've sent a few inquiries recently. Please try again in an hour.", foot:"Independent web development. Southern California spirit.", top:"Back to top", rights:"Cronoverse. Built with intention."
 },
 es: {
  nav:["Servicios","Cómo trabajamos","Conversemos"], studio:"DISEÑO Y DESARROLLO WEB · SUR DE CALIFORNIA", title:["Raíces locales.","Posibilidades","digitales."], intro:"Tu negocio tiene algo especial. Creemos un sitio web que lo muestre y ayude a que las personas indicadas te encuentren.", cta:"Creemos algo juntos", explore:"Explora los servicios", note:"Tu visión. Diseño con intención. Código a medida.", photo:"CALIFORNIA. UNA NUEVA PERSPECTIVA.", badge:["Las buenas ideas","hablan tu idioma."], band:"Para los negocios que le dan vida al sur de California.", regions:"Orange County · Los Ángeles · San Diego · Inland Empire",
  eyebrow:"01 / LO QUE HACEMOS", heading:"Un mejor espacio\npara tu negocio en línea.", serviceIntro:"¿Empiezas de cero o buscas dar el siguiente paso? Construyamos lo que tu negocio necesita, con espacio para crecer.", services:[
   {title:"Sitios con propósito.",desc:"Un sitio web con personalidad que cuente tu historia y convierta el interés en una conversación.",tags:["Sitios para negocios","Páginas de aterrizaje","Diseño para móviles"]},
   {title:"Una nueva imagen.",desc:"Que un sitio anticuado no te frene. Dale a tu negocio un mensaje más claro y una mejor experiencia.",tags:["Rediseño web","Velocidad y usabilidad","Estructura de contenido"]},
   {title:"Más que una página.",desc:"Cuando tu negocio necesita más, conectamos las herramientas y los procesos que hacen avanzar tu día.",tags:["Aplicaciones web","Integraciones","Herramientas de trabajo"]}
  ], serviceCta:"Cuéntanos qué necesitas", whyEyebrow:"02 / PENSADO PARA TI", whyTitle:"Una muestra de\nlo que es posible.", whyText:"Explora ejemplos interactivos de las páginas y herramientas que podemos crear para tu negocio. Prueba los controles, descubre lo que te sirve y cuéntanos tu idea, en español o inglés.", whyItems:["Comunicación directa con tu desarrollador","Un alcance claro antes de empezar","Diseñado para tus clientes, en cada pantalla"], languageSmall:"DESDE EL PRIMER HOLA HASTA EL LANZAMIENTO.", processEyebrow:"03 / PASO A PASO", processTitle:"Grandes ideas. Pasos claros.", steps:[
   {title:"Conversemos.",text:"Cuéntanos de tu negocio, tus clientes y lo que quieres lograr con tu sitio web."},
   {title:"Hagámoslo tuyo.",text:"Definimos el alcance, exploramos el diseño y construimos tu sitio con espacio para tus comentarios."},
   {title:"Al mundo.",text:"Revisamos los detalles, conectamos tu dominio y te mostramos cómo funciona tu nuevo sitio."}
  ], contactEyebrow:"04 / TU PRÓXIMO CAPÍTULO", contactTitle:"Algo grande\nempieza con un hola.", contactText:"Un nuevo negocio. Un cambio pendiente. Una idea en una servilleta. Cuéntanos lo que tienes en mente.", contactNote:"Español o English. Como te sientas más cómodo.", name:"Tu nombre", email:"Correo electrónico", business:"Nombre del negocio (opcional)", need:"¿En qué podemos ayudarte?", choose:"Elige un servicio", options:["Un sitio web nuevo","Rediseñar mi sitio","Una aplicación o integración","Descubrámoslo juntos"], project:"Cuéntanos un poco de tu proyecto", placeholder:"¿A qué te dedicas y qué te gustaría crear?", submit:"Enviar consulta", sending:"Enviando tu consulta…", privacy:"Al enviar, aceptas que te contactemos sobre tu proyecto. Guardaremos tus datos para gestionar esta consulta.", success:"Tu próximo capítulo ya empezó.", successText:"Guardamos tu consulta. Usaremos el correo que nos diste para conversar sobre tu proyecto.", again:"Enviar otra consulta", error:"No pudimos guardar tu consulta. Inténtalo de nuevo; tus datos siguen aquí.", rate:"Ya enviaste varias consultas. Inténtalo de nuevo en una hora.", foot:"Desarrollo web independiente. Espíritu californiano.", top:"Volver arriba", rights:"Cronoverse. Creado con intención."
 }
};
const ids = ["new","redesign","app","unsure"];
function makeInquiryId(){
 if(typeof crypto.randomUUID === "function") return crypto.randomUUID();
 const bytes=crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;
 const hex=Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");
 return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
}

export default function Home(){
 const [lang,setLang]=useState<Language>("en"); const [menu,setMenu]=useState(false); const [service,setService]=useState("");
 const [status,setStatus]=useState<"idle"|"sending"|"success"|"error"|"rate">("idle"); const form=useRef<HTMLFormElement>(null); const requestId=useRef(""); const t=copy[lang];
 useEffect(()=>{const q=new URLSearchParams(location.search).get("lang");let saved="";try{saved=localStorage.getItem("cronoverse-language")||"";}catch{}if(q==="es"||(q!=="en"&&saved==="es"))setLang("es");},[]);
 useEffect(()=>{document.documentElement.lang=lang;},[lang]);
 function language(v:Language){setLang(v);try{localStorage.setItem("cronoverse-language",v);}catch{}const url=new URL(location.href);url.searchParams.set("lang",v);history.replaceState(null,"",url);}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==="sending")return;const data=new FormData(e.currentTarget);if(!requestId.current)requestId.current=makeInquiryId();setStatus("sending");try{const r=await fetch("/api/inquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:requestId.current,name:data.get("name"),email:data.get("email"),business:data.get("business"),message:data.get("message"),website:data.get("website"),service:service||"unsure",language:lang})});setStatus(r.ok?"success":r.status===429?"rate":"error");}catch{setStatus("error");}}
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:object,options:object)=>void|Promise<void>}}).modelContext;if(!ctx)return;const life=new AbortController();try{void Promise.resolve(ctx.registerTool({name:"start_project_inquiry",description:"Open the project inquiry form and optionally select a service. Does not submit an inquiry.",inputSchema:{type:"object",properties:{service:{type:"string",enum:ids}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object"||Array.isArray(input))throw new Error("Expected an object");const value=(input as {service?:string}).service;if(Object.keys(input).some(k=>k!=="service")||(value!==undefined&&!ids.includes(value)))throw new Error("Invalid service");if(value)setService(value);document.getElementById("contact")?.scrollIntoView({behavior:"instant"});await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return{status:"form_opened",submitted:false};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 return <>
  <a className="skip-link" href="#main">{lang==="en"?"Skip to content":"Ir al contenido"}</a>
  <div className="dark-intro" id="top">
   <header className="site-header wrap"><a className="wordmark" href="#top" aria-label="Cronoverse home"><span className="brand-mark" aria-hidden="true"><img src="/cronoverse-saturn-eye-navy.png" alt="" width="64" height="64"/></span>cronoverse</a><nav className="desktop-nav" aria-label={lang==="en"?"Main navigation":"Navegación principal"}><a href="#services">{t.nav[0]}</a><a href="#approach">{t.nav[1]}</a></nav><div className="header-actions"><div className="language-control" aria-label="Language / Idioma"><button type="button" aria-pressed={lang==="en"} onClick={()=>language("en")}>EN</button><span>/</span><button type="button" aria-pressed={lang==="es"} onClick={()=>language("es")}>ES</button></div><a className="header-cta" href="#contact">{t.nav[2]}<ArrowUpRight size={17}/></a><button className="menu-toggle" type="button" aria-expanded={menu} aria-controls="mobile-nav" aria-label={lang==="en"?"Toggle navigation":"Abrir navegación"} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
   {menu&&<nav id="mobile-nav" className="mobile-nav" aria-label="Mobile"><a onClick={()=>setMenu(false)} href="#services">{t.nav[0]}</a><a onClick={()=>setMenu(false)} href="#approach">{t.nav[1]}</a><a onClick={()=>setMenu(false)} href="#contact">{t.nav[2]}</a></nav>}
   <main id="main"><section className="hero wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="tiny-line"/>{t.studio}</p><h1 id="hero-title">{t.title[0]}<br/>{t.title[1]}<br/><span>{t.title[2]}</span></h1><p className="hero-description">{t.intro}</p><div className="hero-actions"><a className="button button-electric" href="#contact"><DustSurface variant="button" phase={2.5}/>{t.cta}<ArrowUpRight size={20}/></a><a className="text-link" href="#services">{t.explore}<ArrowRight size={16}/></a></div><p className="hero-note">{t.note}</p></div><div className="hero-visual"><img src="/hero-digital-palms.png" width="1254" height="1254" alt={lang==="en"?"Surreal illustrated California palm trees with electric-blue edges and digital fragments above a coral sunset":"Ilustración surrealista de palmeras californianas con bordes azul eléctrico y fragmentos digitales sobre un atardecer coral"} fetchPriority="high"/><div className="photo-shade"/><div className="photo-top"><span>SOUTHERN<br/>CALIFORNIA</span><Compass size={28} strokeWidth={1}/></div><div className="photo-bottom"><span>{t.photo}</span><span>SC / 01</span></div><div className="language-sticker"><DustSurface variant="badge" phase={.7}/><Globe2 size={22} strokeWidth={1.5}/><div><span className="sticker-label">ENGLISH + ESPAÑOL</span><p>{t.badge[0]}<br/>{t.badge[1]}</p></div></div></div></section><div className="region-band"><div className="wrap"><span>{t.band}</span><span>{t.regions}</span></div></div></main>
  </div>
  <section className="services-section section-pad" id="services" aria-labelledby="services-title"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">{t.eyebrow}</p><h2 id="services-title">{t.heading}</h2></div><p className="section-description">{t.serviceIntro}</p></div><div className="service-grid">{t.services.map((item,i)=>{const Icon=[Layers3,Smartphone,Code2][i];return <article className="service-card" key={i}><div className="service-top"><Icon size={28} strokeWidth={1.3}/><span>0{i+1}</span></div><h3>{item.title}</h3><p>{item.desc}</p><ul>{item.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><a className="service-link" href="#contact" onClick={()=>setService(ids[i])}>{t.serviceCta}<ArrowUpRight size={18}/></a></article>})}</div></div></section>
  <section className="approach-section section-pad" id="approach" aria-labelledby="approach-title"><div className="wrap approach-grid"><CapabilityShowcase lang={lang}/><div className="approach-copy"><p className="eyebrow">{t.whyEyebrow}</p><h2 id="approach-title">{t.whyTitle}</h2><p>{t.whyText}</p><ul>{t.whyItems.map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul></div></div></section>
  <section className="process-section section-pad" aria-labelledby="process-title"><div className="wrap"><p className="eyebrow">{t.processEyebrow}</p><h2 id="process-title">{t.processTitle}</h2><div className="process-grid">{t.steps.map((step,i)=><article key={i}><span className="step-number">0{i+1}</span><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></div></section>
  <section className="contact-section section-pad" id="contact" aria-labelledby="contact-title"><div className="wrap contact-grid"><div className="contact-copy"><p className="eyebrow">{t.contactEyebrow}</p><h2 id="contact-title">{t.contactTitle}<span className="dust-underline" aria-hidden="true"><DustSurface variant="line" color="var(--signal)" phase={1}/></span></h2><p>{t.contactText}</p><div className="contact-language"><Globe2 size={20}/><span>{t.contactNote}</span></div><ArrowUpRight className="contact-arrow" size={116} strokeWidth={.7}/></div><div className="form-panel">{status==="success"?<div className="success-panel" role="status"><span className="success-check"><Check size={30}/></span><h3>{t.success}</h3><p>{t.successText}</p><button className="button button-dark" type="button" onClick={()=>{setStatus("idle");setService("");requestId.current=""}}>{t.again}<ArrowRight size={17}/></button></div>:<form ref={form} onSubmit={submit} className="inquiry-form"><div className="form-row"><label htmlFor="name">{t.name}<Input id="name" name="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="Alex Rivera"/></label><label htmlFor="email">{t.email}<Input id="email" name="email" type="email" required maxLength={254} autoComplete="email" placeholder={lang==="en"?"you@yourbusiness.com":"tu@tunegocio.com"}/></label></div><label htmlFor="business">{t.business}<Input id="business" name="business" maxLength={160} autoComplete="organization"/></label><div className="field-label"><label id="service-label" htmlFor="service">{t.need}</label><Select value={service} onValueChange={setService} name="service"><SelectTrigger id="service" aria-labelledby="service-label" className="service-select"><SelectValue placeholder={t.choose}/></SelectTrigger><SelectContent>{t.options.map((option,i)=><SelectItem key={ids[i]} value={ids[i]}>{option}</SelectItem>)}</SelectContent></Select></div><label htmlFor="message">{t.project}<Textarea id="message" name="message" required minLength={10} maxLength={4000} rows={4} placeholder={t.placeholder}/></label><div className="honey" aria-hidden="true"><label htmlFor="website">Website<Input id="website" name="website" tabIndex={-1} autoComplete="off"/></label></div>{(status==="error"||status==="rate")&&<p className="form-error" role="alert">{status==="rate"?t.rate:t.error}</p>}<button type="submit" disabled={status==="sending"} className="button button-dark submit-button">{status==="sending"?t.sending:t.submit}{status==="sending"?<LoaderCircle className="spinner" size={19}/>:<ArrowUpRight size={19}/>}</button><p className="privacy-note">{t.privacy}</p></form>}</div></div></section>
  <footer className="site-footer"><div className="wrap"><div className="footer-top"><a className="wordmark" href="#top"><span className="brand-mark" aria-hidden="true"><img src="/cronoverse-saturn-eye-navy.png" alt="" width="64" height="64"/></span>cronoverse</a><p>{t.foot}</p><a className="footer-back" href="#top">{t.top}<ArrowUpRight size={16}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {t.rights}</span><span>Southern California · English & Español</span></div></div></footer>
 </>;
}
