# Generated by Django 6.1.1 on 2026-09-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('business', models.CharField(blank=True, default='', max_length=160)),
                ('service', models.CharField(choices=[('new', 'New website'), ('redesign', 'Website redesign'), ('app', 'Web app / integration'), ('unsure', 'Not sure yet')], default='unsure', max_length=20)),
                ('message', models.TextField(max_length=4000)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2)),
                ('source', models.CharField(default='contact_section', help_text='Internal tag for which page/section this lead came from.', max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('WON', 'Won'), ('LOST', 'Lost'), ('SPAM', 'Spam')], default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='leads_lead_email_2975bd_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx')],
            },
        ),
    ]
