# Generated by Django 5.2.18 on 2026-10-07 16:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeGuard',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('business', models.CharField(blank=True, max_length=160)),
                ('service', models.CharField(choices=[('new', 'New website'), ('redesign', 'Website redesign'), ('app', 'Web app or integration'), ('unsure', "Let's figure it out together")], max_length=16)),
                ('message', models.TextField(max_length=4000)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True, help_text='Internal notes; never included in customer emails.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Project inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='inquiry_email_created'), models.Index(fields=['status', 'created_at'], name='inquiry_status_created')],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('welcome', 'Customer welcome'), ('notification', 'Owner notification')], max_length=16)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('retry', 'Waiting to retry'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(editable=False, null=True)),
                ('locked_until', models.DateTimeField(editable=False, null=True)),
                ('last_error', models.CharField(blank=True, help_text='Error type only; no email contents or credentials.', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('sent_at', models.DateTimeField(editable=False, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='inquiries.inquiry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='email_ready')],
                'constraints': [models.UniqueConstraint(fields=('inquiry', 'kind'), name='one_email_per_inquiry_kind')],
            },
        ),
    ]
